### ISSUE TITLE
Cannot build local copy of repo due to symlinks in the repo

### ISSUE THREAD

**Issue by jnolan14** [rohitrango/FireANTs#12]
There seem to be 2 files missing from the source:
- fireants/scripts/evalutils.py
- fireants/scripts/lookup_tables.py

Where can I access these files to complete the source tree?
Are these files actually needed to run the core functionality? 
It seems that the lookup_table functionality is not used anywhere, and the evalutils are only referenced in the oasis.py file.

**Comment by rohitrango** [comment]
Hi, 


You do not need the two files to run the core functionality, they are useful just to reproduce the results in the paper.


evalutils.py uses lookup_tables.py so thats the other file.

try running without the symlinks, it should work.

**Comment by jnolan14** [comment]
Thank you for the quick response and confirming that these links can be dropped.
That got the install working!
