### ISSUE TITLE
[Enhancement]: Small Addition - Save Moved Image as NIfTI in Tutorial

### ISSUE THREAD

**Issue by LalithShiyam** [rohitrango/FireANTs#3]
Hi @rohitrango,

Thank you for the fantastic work on FireANTs - it's blazingly fast! I've made a small addition to the tutorial that I think could be helpful. The update allows users to save the moved image as a NIfTI file, ensuring it retains the correct spatial metadata from the reference image.

I noticed that similar functionality exists elsewhere in the codebase, but I thought incorporating it into the tutorial could enhance usability. I've also submitted a PR—please feel free to review it if you think this contribution would be valuable.

Thanks again!

Cheers,
Lalith

**Comment by rohitrango** [comment]
Thanks Lalith, 

> As promised I tested the package (FireAnts), and as advertised, it is fast and delightful to work with.

Feedback like yours truly makes the package better and more usable to work with. I will take a look at the other PR more carefully once my schedule frees up a bit (next week). 

> If this package is in active development, I am happy to give some feedback + request some features (happy to contribute as well), which would make it way cooler than it is now.

Yes, the package is in active development along with the [preprint](https://arxiv.org/abs/2404.01249), and community feedback will only make it more fast and usable to work with. Feel free to open issues/PRs that improve the package.

Couple of more ways you can contribute is by citing our paper in your research, and sharing the library with your colleagues and such, as word-of-mouth can be extremely beneficial for growth of a nascent library like this. 

Cheers!

**Comment by rohitrango** [comment]
actually the PR was pretty straightforward, so I merged it.

Thank you for the contribution! 🎉

**Comment by LalithShiyam** [comment]
Fantastic, happy to do so. In the next few weeks, I will perform some more NIREP evaluations on our total-body PET/CT datasets and provide you with feedback. Honestly, if things keep going this smoothly, we might just swap out native greedy for your package—and trust me, I'll be singing its praises to anyone with ears!
