### ISSUE TITLE
[Discussion]: Expanding FireANTs Support to MPS and License Clarification

### ISSUE THREAD

**Issue by LalithShiyam** [rohitrango/FireANTs#6]
Hi @rohitrango, 

Sorry about the spam, I am just excited 🥳. I originally wanted to post this under `Discussions` but I think it hasn't been enabled in the repo. Anyway - `FireANTs` is providing a significant speed-up due to the Torch+CUDA implementation, which is fantastic. Since PyTorch now supports MPS (Metal Performance Shaders) on macOS, I was wondering if there are any plans to extend FireANTs' support to MPS as well? This could be particularly beneficial for users on Apple Silicon.

Additionally, I noticed that the package doesn’t currently have a specified license. Would you be kind enough to clarify what license `FireANTs` is distributed under?

Cheers,
Lalith

**Comment by rohitrango** [comment]
No problem haha. I've enabled the Discussions section. 

MPS support: this is slightly low-priority as of now because I'm still trying to get mostly power users onboarded first. But if you can work on MPS support and give some Perf metrics, that would be excellent! Nothing better than a registration algorithm that also runs fast on the newer macs!  

I will update the license soon.

**Comment by rohitrango** [comment]
updated the license

**Comment by LalithShiyam** [comment]
Happy to do so. We just figured out MPS for one of the packages. It's pretty good. I am happy to look into this and keep you posted.

**Comment by rohitrango** [comment]
An update on MPS support: it looks like the MPS backend does not support crucial ops like F.conv3d yet 

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/385de7c1-8124-41d3-bd77-93e045917f59" />

this leads to the method simply falling back to CPU. This is a bummer but we have to wait for PyTorch devs to implement these ops (or do it ourselves - and I dont have the bandwidth to do it).

**Comment by LalithShiyam** [comment]
Hi @rohitrango, 

You are right. But we have a fork for that. I haven't forgotten about this. Conv3d and transposeconv3d is available on this fork:

git+https://github.com/LalithShiyam/pytorch-mps.git

I am in transition, so busy sorting out things. But this is definitely on my priority list!

**Comment by rohitrango** [comment]
sounds exciting! In that case, I'll put you in charge of MPS support for FireANTs (mostly just the interpolation and conv operations)

Good luck with your move!

**Comment by LalithShiyam** [comment]
🫡🫡

**Comment by rohitrango** [comment]
Ideally you should not need to put it anywhere because by default all registration objects (variables, intermediaries, ops) live on the same device as the images

**Comment by LalithShiyam** [comment]
Hi @rohitrango,

You were right—after moving all new tensors onto the anchor tensor’s device, the whole pipeline now runs on mps + Conv3d works with this [pytorch-mps ](https://github.com/LalithShiyam/pytorch-mps.git)fork.

The only remaining message is a warning about upsample_trilinear3d falling back to CPU:

```
~/pytorch-mps/torch/nn/functional.py:4068: UserWarning:
aten::upsample_trilinear3d.out will fall back to CPU
```

Even though it falls back on CPU, it's not too bad. I will give concrete numbers in a bit.

I feel bad for not looking at this for so long, it was a simple patch...

Sorry.

Lalith

**Comment by LalithShiyam** [comment]
Ofcourse :) thanks for understanding!
